package com.email.writer;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import org.springframework.web.reactive.function.client.WebClient;
import org.springframework.web.reactive.function.client.WebClientResponseException;
import tools.jackson.databind.JsonNode;
import tools.jackson.databind.ObjectMapper;
import tools.jackson.databind.node.ObjectNode;
import tools.jackson.databind.node.ArrayNode;

import java.time.Duration;
import reactor.util.retry.Retry;

@Service
public class EmailGeneratorService {

    private final WebClient webClient;
    private final String apiKey;
    private final ObjectMapper objectMapper;

    public EmailGeneratorService(WebClient.Builder webClientBuilder,
                                 @Value("${gemini.api.url}") String baseUrl,
                                 @Value("${gemini.api.key}") String geminiApiKey) {
        this.webClient = webClientBuilder
                .baseUrl(baseUrl)
                .defaultHeader("Content-Type", "application/json")
                .build();
        this.apiKey = geminiApiKey;
        this.objectMapper = new ObjectMapper();
    }

    public String generateEmailReply(EmailRequest emailRequest) {
        try {
            String prompt = buildPrompt(emailRequest);
            String requestBody = buildRequestBody(prompt);

            String response = webClient.post()
                    .uri(uriBuilder -> uriBuilder
                            .path("/v1beta/models/gemini-3-flash-preview:generateContent")
                            .queryParam("key", apiKey)
                            .build())
                    .bodyValue(requestBody)
                    .retrieve()
                    .bodyToMono(String.class)
                    .retryWhen(Retry.backoff(3, Duration.ofSeconds(2))
                            .filter(throwable -> throwable instanceof WebClientResponseException.TooManyRequests))
                    .timeout(Duration.ofSeconds(30))
                    .block();

            return extractResponseContent(response);

        } catch (WebClientResponseException.TooManyRequests e) {
            throw new RuntimeException("Rate limit exceeded. Please wait a moment and try again.", e);
        } catch (WebClientResponseException e) {
            throw new RuntimeException("API error: " + e.getStatusCode() + " - " + e.getResponseBodyAsString(), e);
        } catch (Exception e) {
            throw new RuntimeException("Failed to generate email reply: " + e.getMessage(), e);
        }
    }

    private String buildRequestBody(String prompt) {
        try {
            ObjectNode root = objectMapper.createObjectNode();
            ArrayNode contents = objectMapper.createArrayNode();
            ObjectNode content = objectMapper.createObjectNode();
            ArrayNode parts = objectMapper.createArrayNode();
            ObjectNode part = objectMapper.createObjectNode();

            part.put("text", prompt);
            parts.add(part);
            content.set("parts", parts);
            contents.add(content);
            root.set("contents", contents);

            return objectMapper.writeValueAsString(root);
        } catch (Exception e) {
            throw new RuntimeException("Failed to build request body", e);
        }
    }

    private String extractResponseContent(String response) {
        try {
            JsonNode root = objectMapper.readTree(response);

            // Check if there's an error in the response
            if (root.has("error")) {
                String errorMessage = root.path("error").path("message").asText("Unknown error");
                throw new RuntimeException("Gemini API error: " + errorMessage);
            }

            // Extract the generated text
            JsonNode candidates = root.path("candidates");
            if (candidates.isEmpty()) {
                throw new RuntimeException("No response generated by the API");
            }

            String generatedText = candidates.get(0)
                    .path("content")
                    .path("parts")
                    .get(0)
                    .path("text")
                    .asText();

            if (generatedText == null || generatedText.isEmpty()) {
                throw new RuntimeException("Empty response from API");
            }

            return generatedText;

        } catch (Exception e) {
            throw new RuntimeException("Failed to parse API response: " + e.getMessage(), e);
        }
    }

    private String buildPrompt(EmailRequest emailRequest) {
        StringBuilder prompt = new StringBuilder();

        prompt.append("You are a professional email assistant. Generate a clear, concise, and professional reply to the following email which do not contain Subject.\n\n");

        if (emailRequest.getTone() != null && !emailRequest.getTone().isEmpty()) {
            prompt.append("Tone: Use a ").append(emailRequest.getTone()).append(" tone.\n\n");
        }

        prompt.append("Original Email:\n");
        prompt.append(emailRequest.getEmailContent());
        prompt.append("\n\nGenerate only the email reply without any additional explanation or commentary.");

        return prompt.toString();
    }
}




//package com.email.writer;
//
//import org.springframework.beans.factory.annotation.Value;
//import org.springframework.stereotype.Service;
//import org.springframework.web.reactive.function.client.WebClient;
//import tools.jackson.databind.JsonNode;
//import tools.jackson.databind.ObjectMapper;
//
//@Service
//public class EmailGeneratorService {
//
//    private final WebClient webClient;
//    private final String apiKey;
//
//    public EmailGeneratorService(WebClient.Builder webClientBuilder,
//                                 @Value("${gemini.api.url}") String baseUrl,
//                                 @Value("${gemini.api.key}") String geminiApiKey) {
//        this.webClient = webClientBuilder.baseUrl(baseUrl).build();
//        this.apiKey = geminiApiKey;
//    }
//
//    public String generateEmailReply(EmailRequest emailRequest) {
//
//        String prompt = buildPrompt(emailRequest);
//
//        String requestBody = String.format("""
//                {
//                    "contents": [
//                      {
//                        "parts": [
//                          {
//                            "%s"
//                          }
//                        ]
//                      }
//                    ]
//                  }""",prompt);
//
//        String response = webClient.post()
//                .uri(uriBuilder -> uriBuilder
//                        .path("/v1beta/models/gemini-3-flash-preview:generateContent")
//                        .build())
//                .header("x-goog-api-key", apiKey)
//                .header("Content-Type", "application/json")
//                .bodyValue(requestBody)
//                .retrieve()
//                .bodyToMono(String.class)
//                .block();
//
//        return extractResponseContent(response);
//    }
//
//    private String extractResponseContent(String response) {
//        ObjectMapper mapper = new ObjectMapper();
//        JsonNode root = mapper.readTree(response);
//        return root.path("candidates")
//                .get(0)
//                .path("content")
//                .path("parts")
//                .get(0)
//                .path("text")
//                .asString();
//    }
//
//    private String buildPrompt(EmailRequest emailRequest) {
//        StringBuilder prompt = new StringBuilder();
//
//        prompt.append("Generate a professional reply for the following mail: \n");
//
//        if(emailRequest.getTone() != null && !emailRequest.getTone().isEmpty()){
//            prompt.append("Use a ").append(emailRequest.getTone()).append(" for generating the reply. \n");
//        }
//
//        prompt.append(emailRequest.getEmailContent());
//
//        return prompt.toString();
//    }
//}
